### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by abrarahsan16** [ruhacks/RU_2020_frontend#1]
Right now the sponsors appear/pop-up all together when you scroll down, try changing it to reflect the similar way the FAQs show up. Maintains consistency

**Comment by dstingaciu** [comment]
The final version for volunteers and mentors commit adds this enhancement. Thanks for the suggestion! 

Commit: https://github.com/ruhacks/RU_2020_frontend/commit/05dd4efc23eb0ca3e9280c11a88f89b03789e2dc
